version: '3.3'

services:

  db:
    image: postgres:13.0-alpine
    volumes:
      - db_data:/var/lib/postgresql/data/
    env_file:
      - ../.env
    expose:
      - 5433
    command: -p 5433

  web:
    image: mazavrbazavr/yatube:latest
    expose:
      - 8004
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ../.env

  nginx:
    image: nginx:1.19.3
    # ports:
    #   - "80:80"
    expose:
      - 8084
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    environment:
      VIRTUAL_HOST: yatube.mazavrbazavr.ru
      VIRTUAL_PORT: 8081
      LETSENCRYPT_HOST: yatube.mazavrbazavr.ru
      LETSENCRYPT_EMAIL: ilkutil@gmail.com
    restart: always
    depends_on:
      - web

volumes:
  db_data:
  static_value:
  media_value:

networks:
  default:
    external:
      name: nginx-proxy